### ISSUE TITLE
freelanzer.com domain hacked?

### ISSUE THREAD

**Issue by haarp** [KuriKai/DHTP#14]
Hi,

the site seems to be nonfunctional. Additionally, when I go to the freelanzer.com root, there is an obfuscated redirect in the page source which leads to:

META http-equiv="refresh" content="1;URL=hxtxtxp://win.gft-adobe.com/flashplayer/en/"

(I changed it so it's not clickable) This is extremely likely to be **malware**!

Are you the owner of this domain, or do you know him? Should really have a look at that.

**Comment by KuriKai** [comment]
Moved from freelanzer.com to hirwa.com as freelanzer.com host was cancled
