### ISSUE TITLE
Doom TNT: Evilution - Weird stretched skies

### ISSUE THREAD

**Issue by HazyHills** [KuriKai/DHTP#15]
I am having an issue with DHTP on Doom TNT, basically the Doom 1 skies that display are showing really stretched, like this:

![c1cb4b758d](https://cloud.githubusercontent.com/assets/4315982/7936258/9b0605a8-092f-11e5-9776-869d02f9bb09.jpeg)
![652db350e3](https://cloud.githubusercontent.com/assets/4315982/7936312/f6266c0c-092f-11e5-8831-a1021e439b79.jpeg)

Any of you guys know how to solve this?  I am using Zandronum.

**Comment by KuriKai** [comment]
The skys need to be created

**Comment by HazyHills** [comment]
Ahhh, I see.  It's OK, in the meantime I created some placeholder textures which are just the doom 1 skies tiled.  Comes out alright.

![95cf4dfdab](https://cloud.githubusercontent.com/assets/4315982/7995794/6e229946-0b11-11e5-8934-6a624e6f8dd8.jpeg)
