### ISSUE TITLE
[GZDoom] - Doom2, Level2 (sw1comm & sw2comm)

### ISSUE THREAD

**Issue by swc132994** [KuriKai/DHTP#19]
I noticed there is a misalignment on the the sw1comm and sw2comm textures playing Doom 2

![sw1comm](https://cloud.githubusercontent.com/assets/10770202/9005427/a6ad944a-376d-11e5-8835-5e91daffafc4.png)
Doom2 Level2
![sw2comm](https://cloud.githubusercontent.com/assets/10770202/9005436/bb847442-376d-11e5-8fa6-9f7585aa859c.png)
Doom2 Level2

The Hires texture images in the pack looks fine though
![sw1comm](https://cloud.githubusercontent.com/assets/10770202/9005495/3097a97a-376e-11e5-85a9-718c4f729559.png)
![sw2comm](https://cloud.githubusercontent.com/assets/10770202/9005499/39562afa-376e-11e5-9b12-33bc9f679e6d.png)

**Comment by Piter432** [comment]
This is problem with brightmaps, which were made for original Doom textures. Currently there are no brightmaps for hi-res textures.

**Comment by KuriKai** [comment]
Looks like the DHTP texture switch is in the wrong location compared with the original.
I will ahve to leave it how it is until a higher res metal texture can be made, so the new set of higher resolution switches can be used

**Comment by KuriKai** [comment]
Fixed versions have been uplaoded to github, thanks to Kars.
They will be in the next release.
