### ISSUE TITLE
[build scripts] tex-all.sh fails to compile zdoom pack

### ISSUE THREAD

**Issue by KuriKai** [KuriKai/DHTP#23]
seems at the end of the r3d pack script the path gets changed to ./ instead of ./DHTP/

which breaks the running of the zdoom script

running the zdoom script by itself compiles the pack successfully

**Comment by radavis** [comment]
The instructions in the README.md state you should run the build command from the root path of the project. This is rather typical for most projects I've worked on.

```
$ git clone git@github.com:KuriKai/DHTP.git dhtp-original
$ cd dhtp-original
$ ./build/tex-all.sh
$ ls -la built
-rw-r--r--   1 rd  staff  256029813 Dec 27 15:02 deng-dhtp-20151227.pk3
-rw-r--r--   1 rd  staff  253027280 Dec 27 15:02 r3d-dhtp-20151227.zip
-rw-r--r--   1 rd  staff  252931328 Dec 27 15:02 zdoom-dhtp-20151227.pk3
```

I reverted back to a commit from before any of my commits were merged in to master, and tried to build all from the root project folder. Here's what I got:

```
$ git reset --hard ac609f
$ git clean -f
$ rm -rf zdoom
$ rm -rf risen3d
$ rm -rf doomsday
$ ./build/tex-all.sh
----Starting Doomsday pack----
...
---------Complete---------
----starting Risen3d pack----
./build/tex-all.sh: line 24: /tex-r3d.sh: No such file or directory
----starting zdoom pack----
./build/tex-all.sh: line 27: /tex-zd.sh: No such file or directory
```
