### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by NullWir3** [KuriKai/DHTP#26]
Well in Ultimate Doom there are a missing textures, in the map e2m8 ¨Tower of Babel¨ the textures of tortured barons are missing (Not in hi res)

This one is from the Icon of Sin on the map 30 of Doom 2, there is no actual hi res version for them.
Not in the actual and past versions of the mod

My question is.. You gonna add the textures ofr this two?

**Comment by KuriKai** [comment]
tortured barons are currently a work in progress, I'm also working on a model pack, so things take a while.

Icon of sin is a big effort to do
