### ISSUE TITLE
Doom Plutonia experiment ¨Root¨ walls

### ISSUE THREAD

**Issue by NullWir3** [KuriKai/DHTP#27]
In Plutonia you gonna add the textures for the green root walls?

Anyway my main question is; you gonna add the textures for the final doom?

**Comment by KuriKai** [comment]
after doom1 and doom2 are complete

**Comment by eGax** [comment]
![a-vine3](https://cloud.githubusercontent.com/assets/9817245/13002449/9901a32c-d13c-11e5-91cc-74446b312cec.png)

**Comment by KuriKai** [comment]
Thanks for that, that texture will be in the next pack
