### ISSUE TITLE
Website no longer valid

### ISSUE THREAD

**Issue by SibTiger** [KuriKai/DHTP#31]
It seems that the website provided in the README.md `http://dhtp.hiriwa.com/` no longer works as it provides a `401` error through Dropbox's service.

This effects some topics as well: [Zandronum](https://zandronum.com/forum/viewtopic.php?p=84196#p84196), [DE Forum](http://dengine.net/forums/viewtopic.php?f=3&t=875#topic)

**Comment by KuriKai** [comment]
Thanks, I didn't notice

I have updated it to direct to the wiki page github

**Comment by SibTiger** [comment]
Thank you!
