### ISSUE TITLE
Simplifying the ZDoom/GZDoom version of the pack again

### ISSUE THREAD

**Issue by Dranyth** [KuriKai/DHTP#32]
I don't know if this was added recently to the ZDoom wiki or if the information was just clarified, but I've confirmed that filtering now works on archives, so if you wanted to, you could update the ZDoom texture pack build to make it much more simple as just a single file.  The folder structure would work as follows:

> filter
> filter/doom/hires
> filter/doom.doom2/hires
> filter/doom.doom2.plutonia/hires
> filter/doom.doom2.tnt/hires

Your Readme files would simply go in the 'filter' folder and the textures themselves would go inside the 'hires' folders inside their respective directories.

This would greatly simplify installation for the end users as they'd then only have to insert the path to one PK3 file into the [doom.Autoload] section of their ZDoom/GZDoom INI file.

I don't know if it was like this before and I just misunderstood it or what, but it definitely works now.

**Comment by KuriKai** [comment]
https://mega.nz/#!F5pG0IYD!IRRsuWSJsphI66gFJA9LHxNTgHX7R7nNkDn7aHETkRc
does this work?

**Comment by Dranyth** [comment]
Just gave it a shot, renamed it to a .PK3 and it worked fine.  I also messed up slightly, the Readme files can actually go up one level in the root level folder instead of the 'filter' folder.  They don't hurt anything where they are either, they'd just be more visible, though I guess end users don't really open PK3 files anyway.

But yeah, just make it a .PK3 instead of a .ZIP and it'll be all ready to go.  Sorry for the trouble, but when I discovered that the filtering did work inside of archives now, I thought it was worth making it easier for other people wanting to use the hires textures with ZDoom/GZDoom.

**Comment by KuriKai** [comment]
ok, this should be all good.
Test it out and i will make it the latest release if it's good
https://mega.nz/#!VtIhAT5J!lwhcQTE73zDkVyW8nlwNm0zU4w_AWTZhPsErKfjSjoc

Also what's the new way for zdoom users to load it? (need to update the documentation)

**Comment by Dranyth** [comment]
Perfect!

Alright, luckily the installation instructions are waaay simpler now.  We can probably just go with something like:

## ZDoom or GZDoom

1. Place in your ZDoom or GZDoom folder
2. Edit your zdoom-\<username\>.ini or gzdoom-\<username\>.ini with a text editor
3. Scroll down to the [doom.Autoload] header and add the following line so that it looks like this:
```
[doom.Autoload]
Path=$PROGDIR/zdoom-dhtp-20161017.pk3
```
The filename may need to be updated if a newer version of the texture pack comes out, but all hires textures will now be correctly loaded by the version of Doom/Doom2 being run.  The issues of glitching animated textures like waterfalls and incorrect skies should now be resolved.

**Comment by KuriKai** [comment]
closing as issue seems to be fixed now

**Comment by r6d2** [comment]
On the zdoom-dhtp-20171001.pk3 release the old un-filtered structure seems to be used again.
https://gyazo.com/4cc627d1def809b9516b5008aac1dffc

Was this change revoked?

**Comment by KuriKai** [comment]
Quite strange, I guess I must have uploaded the wrong build, back when i closed this issue, and no one mentioned anything. Tried building it now and it's fine. Uploading now

**Comment by r6d2** [comment]
Thanks, it worked.
