### ISSUE TITLE
Grass

### ISSUE THREAD

**Issue by Nipless** [KuriKai/DHTP#33]
Hello I was playing a map and I came across this
![screenshot_doom_20161216_125523](https://cloud.githubusercontent.com/assets/24610117/21269804/f5e92c74-c392-11e6-8b43-5afdad661047.png)

Where are the bricks supposedly had grass

**Comment by eGax** [comment]
What wad and map is that picture from?

**Comment by Nipless** [comment]
The Journey
(https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/tj)

MAP03

**Comment by KuriKai** [comment]
Closing as not an issue.
Reason: It is a pwad with custom graphics.

I suggest you use a doom engine that does not allow external resources to overwrite pwad custom textures

**Comment by eGax** [comment]
@Nipless not sure what engine your running, but I see grass on gzdoom 2.2.0 and zandronum 2.1.2. There is no issue on my end.

![image](https://cloud.githubusercontent.com/assets/9817245/21293294/b3401f34-c4ed-11e6-8181-bd50cdc11e40.png)

**Comment by Nipless** [comment]
sorry for the inconvenience

**Comment by Nipless** [comment]
I use gzdoom too, maybe it was the order I put it
