### ISSUE TITLE
Download and forum links dead. Here's an alternative.

### ISSUE THREAD

**Issue by MarkJeronimus** [KuriKai/DHTP#37]
https://www.wad-archive.com/wad/77520bc0e0baae5d2273365aad8276ee

**Comment by KuriKai** [comment]
What forum link?
The download link works for me
More information please

**Comment by MarkJeronimus** [comment]
Download link seems to work again.

Forum: http://dengine.net/forums/viewtopic.php?f=3&t=875#topic -> "Not Found"

**Comment by KuriKai** [comment]
Thanks, I have fixed the forums link
