### ISSUE TITLE
GZDoom v1.8.2: DHTP v20140616 + Brutal Doom v19 (or v20 test 10062014)

### ISSUE THREAD

**Issue by JustReportBug** [KuriKai/DHTP#9]
Some GZDoom’s settings was modified. Doom 1, Ultimate, 2: HoE and TNT: Evilution are ok. Problem is only with The Plutonia Experiment.

[IWADSearch.Directories]
Path=PLUTONIA.WAD
&#35; (CRC32: 48D1453C), start of MAP01
[Doom.Autoload]
Path=zdoom-dhtp-20140616.pk3
Path=brutal20test10062014c.pk3
![aplutonia](https://cloud.githubusercontent.com/assets/9446811/4825862/e9cb0fb4-5f69-11e4-9339-b317a7923d76.png)
![bplutonia](https://cloud.githubusercontent.com/assets/9446811/4825866/f088f3c0-5f69-11e4-8b38-af18fe8bd2ff.png)

or:

[Doom.Autoload]
Path=brutal20test10062014c.pk3
Path=zdoom-dhtp-20140616.pk3
![bugplutonia](https://cloud.githubusercontent.com/assets/9446811/4825869/f9774c48-5f69-11e4-873d-cb615961585b.png)

**Comment by KuriKai** [comment]
Is this still a bug?

**Comment by swc132994** [comment]
I do not know about the original poster but I have had no issues with GZDoom, Brutaldoom + DHTP
![2015-07-02_15-57-52](https://cloud.githubusercontent.com/assets/10770202/8480026/d123927e-20ca-11e5-892c-75b387282684.png)
